spring.application.name=Actuator-demo
server.port=8090
#Enabling actuator
management.endpoints.web.exposure.include=helth,info,metrics

#Add app info
management.info.env.enabled=true
info.app.name=Actuator Demo App
info.app.version=1.0
info.app.description=Simple actuator example for fresher
